DROP TABLE IF EXISTS vet_specialties;
DROP TABLE IF EXISTS visits;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS vets;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS specialties;
DROP TABLE IF EXISTS owners;

CREATE TABLE owners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   address VARCHAR(255),
   city VARCHAR(255),
   telephone VARCHAR(255),
   CONSTRAINT pk_owners PRIMARY KEY (id)
);

CREATE TABLE pets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   birth_date date,
   type_id INTEGER,
   owner_id INTEGER,
   CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE specialties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_types PRIMARY KEY (id)
);

CREATE TABLE vet_specialties (
  specialty_id INTEGER NOT NULL,
   vet_id INTEGER NOT NULL,
   CONSTRAINT pk_vet_specialties PRIMARY KEY (specialty_id, vet_id)
);

CREATE TABLE vets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   salary DECIMAL(19, 2),
   CONSTRAINT pk_vets PRIMARY KEY (id)
);

CREATE TABLE visits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   visit_date date,
   description VARCHAR(255),
   vet_id INTEGER,
   pet_id INTEGER,
   CONSTRAINT pk_visits PRIMARY KEY (id)
);

ALTER TABLE pets ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owners (id);

ALTER TABLE pets ADD CONSTRAINT FK_PETS_ON_TYPE FOREIGN KEY (type_id) REFERENCES types (id);

ALTER TABLE visits ADD CONSTRAINT FK_VISITS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE visits ADD CONSTRAINT FK_VISITS_ON_VET FOREIGN KEY (vet_id) REFERENCES vets (id);

ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_specialty FOREIGN KEY (specialty_id) REFERENCES specialties (id);

ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_vet FOREIGN KEY (vet_id) REFERENCES vets (id);
